version: '3'

services:

  # PHP
  php:
    container_name: php_2
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
    volumes:
      - ./public:/var/www/html/
    depends_on:
      - db
    ports:
      - "80:80"

  # MySQL
  db:
    container_name: mysql_host_2
    build: 
      context: .
      dockerfile: ./docker/mysql/dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: roottt
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./public/docker/db/data:/var/lib/mysql
      - ./public/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./public/docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: roottt
    ports:
      - 8081:80
    depends_on:
      - db

